### ISSUE TITLE
Special character handling for container names

### ISSUE THREAD

**Issue by jeremyeder** [rhatdan/atom#6]
Because I did not specify a NAME, it tried to set the container name to the IMAGE name and the IMAGE name has the special characters in it.

```
# docker pull docker-registry...com/vpavlin/rheltools 
94bcddfdb384: Download complete 
root@jerms-lab7: ~ # atomic run docker-registry...com/vpavlin/rheltools df
/usr/bin/docker run -t -i --rm -e CONFDIR=${CONFDIR} -e LOGDIR=${LOGDIR} -e DATADIR=${DATADIR} --name docker-registry.usersys.redhat.com/vpavlin/rheltools docker-registry.usersys.redhat.com/vpavlin/rheltools df
FATA[0000] Error response from daemon: Invalid container name (docker-registry...com/vpavlin/rheltools), only [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
```

Specify a -n flag to make it work:
```
# atomic run -n test docker-registry.usersys.redhat.com/vpavlin/rheltools bash
/usr/bin/docker run -t -i --rm -e CONFDIR=${CONFDIR} -e LOGDIR=${LOGDIR} -e DATADIR=${DATADIR} --name test docker-registry.usersys.redhat.com/vpavlin/rheltools bash
bash-4.2# exit
exit
```

Or tag the image:
```
# docker images | grep rheltools
docker-registry.usersys.redhat.com/vpavlin/rheltools   latest                94bcddfdb384        3 days ago          450.4 MB
# docker tag 94 rheltools
# atomic run --spc rheltools bash
/usr/bin/docker run -t -i --rm --privileged -v /:/host --net=host --ipc=host --pid=host -e HOST=/host -e NAME=rheltools -e IMAGE=rheltools -e CONFDIR=${CONFDIR} -e LOGDIR=${LOGDIR} -e DATADIR=${DATADIR} --name rheltools rheltools bash
bash-4.2# exit
```

**Comment by rhatdan** [comment]
On 01/23/2015 08:56 PM, Jeremy Eder wrote:
>
> Because I did not specify a NAME, it tried to set the container name
> to the IMAGE name and the IMAGE name has the special characters in it.
>
>
>   docker pull docker-registry...com/vpavlin/rheltools
>
> 94bcddfdb384: Download complete
> root@jerms-lab7: ~ # atomic run docker-registry...com/vpavlin/rheltools df
> /usr/bin/docker run -t -i --rm -e CONFDIR=${CONFDIR} -e
> LOGDIR=${LOGDIR} -e DATADIR=${DATADIR} --name
> docker-registry.usersys.redhat.com/vpavlin/rheltools
> docker-registry.usersys.redhat.com/vpavlin/rheltools df
> FATA[0000] Error response from daemon: Invalid container name
> (docker-registry...com/vpavlin/rheltools), only
> [a-zA-Z0-9][a-zA-Z0-9_.-] are allowed
>
I updated the atomic command on github to eliminate the registry and
version if name is not specified.

            self.name = self.image.split("/")[-1].split(":")[0]

atomic run docker-registry.usersys.redhat.com/vpavlin/rheltools:latest
/bin/sh

Ends up with a name of rheltools.
